apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenoid-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenoid-ui
  template:
    metadata:
      labels:
        app: selenoid-ui
    spec:
      containers:
        - name: selenoid-ui
          image: aerokube/selenoid-ui:latest
          args:
            - "--selenoid-uri"
            - "$(SELENOID_URI)"
          env:
            - name: SELENOID_URI
              valueFrom:
                configMapKeyRef:
                  name: configMap
                  key: SELENOID_URI
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: selenoid-ui
spec:
  selector:
    app: selenoid-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort